### ISSUE TITLE
source?

### ISSUE THREAD

**Issue by FrankOcean11** [ofTheo/videoInput#35]
i tried compiling the code in VS2013 and im getting alot of errors how do i go about understanding what this errors get fixed? 

Error	1	error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...".	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets	64	5	videoInput

 i tried looking for that tool but i did not see anything named upgrade? 
![screenshot 167](https://cloud.githubusercontent.com/assets/10504709/14747542/c3a400fc-0882-11e6-8de5-21bb8e5dd3f0.png)

**Comment by ofTheo** [comment]
The VS projects that come with VI are for Visual Studio 2015. 
I think that is where the error is coming from.  You'll need VS 2015 to build VI  

Any reason you are trying to build it vs using the prebuilt libs? 

FYI if you are filing an issue on github its helpful to make the issue title relevant. 
ie: Issue building VideoInput on Visual Studio 2013  :) 

It also makes it easier for people to find via search etc.

**Comment by FrankOcean11** [comment]
i come from Arduino and Processing type of programming so im not really to savvy in VS, i did downloaded VS2013 last year  to mess with this program i found online but thats about it
