### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by MikeGitb** [ofTheo/videoInput#38]
Is this this library/repository still maintained? 

I'm asking, because an ancient version of the source code of this library is used by https://github.com/cinder/Cinder and I thought about updating it. However, I mad a few changes to the cinder version (mostly fixing warnings during build and 1-2 bugs) and -- if possible -- I'd like to upstream those changes here and then pull a clean copy instead of merging the changes in the cinder repo.

However, that would only make sense if I get timely feedback on any PR i might submit.

**Comment by ofTheo** [comment]
Hi. 

Yes if you submit PRs to this upstream I will merge them in. 

I worked a lot on this project in the past but there hasn't been a ton of updates recently. 

I'm all for pulling in bug fixes. 

Thanks for checking in!
Theo

**Comment by MikeGitb** [comment]
Great to hear. Might take a week or two until I can work on this though
