### ISSUE TITLE
deviceNames array overflow

### ISSUE THREAD

**Issue by CodeMarc11** [ofTheo/videoInput#41]
My application was crashing when I put multiple Blackmagic DeckLink cards in my system. I tracked down the cause to videoInput::deviceNames overflowing its array bounds.

The while loop at videoInput.cpp line 840 in listDevices() will iterate until it enumerates all video input devices:

`while (pEnum->Next(1, &pMoniker, NULL) == S_OK)`

However, if you have more than VI_MAX_CAMERAS video input devices present, then line 866:

`deviceNames[deviceCounter][count] = static_cast<char>(varName.bstrVal[count]);`

will end up writing chars past the allocation for deviceNames, corrupting whatever is in memory after the array.

**Comment by ofTheo** [comment]
thanks for the PR!
