### ISSUE TITLE
Can QtMinGW64Bits compile videoInput?

### ISSUE THREAD

**Issue by pcha75** [ofTheo/videoInput#51]
Hello everybody,
I hope you are good.
I have a simple question to ask: I managed to compile videoInput using MSVC19, but when it comes to compile it using QtMinGW64bits, it spits some linking error messages out :
```
/objects.a(VideoInput.cpp.obj):VideoInput.cpp:(.rdata$.refptr.MEDIATYPE_Interleaved[.refptr.MEDIATYPE_Interleaved]+0x0): undefined reference to `MEDIATYPE_Interleaved'
/objects.a(VideoInput.cpp.obj):VideoInput.cpp:(.rdata$.refptr.LOOK_UPSTREAM_ONLY[.refptr.LOOK_UPSTREAM_ONLY]+0x0): undefined reference to `LOOK_UPSTREAM_ONLY'
/objects.a(VideoInput.cpp.obj):VideoInput.cpp:(.rdata$.refptr.IID_IAMCrossbar[.refptr.IID_IAMCrossbar]+0x0): undefined reference to `IID_IAMCrossbar'
```
Has anybody already solved this problem?
Thank you! :)

**Comment by ofTheo** [comment]
We use videoInput in openFrameworks with mingw64 / msys2. 
I think you might just be missing the right linker flags for directshow. 

Did you try building with make? 
This is how we build it for mingw64/32:
https://github.com/openframeworks/apothecary/blob/master/apothecary/formulas/videoInput.sh#L45-L48

You could also try grabbing the libs from the OF release here: 
https://openframeworks.cc/versions/v0.11.2/of_v0.11.2_msys2_mingw64_release.zip

**Comment by pcha75** [comment]
Thank you for your reply!
>Did you try building with make?

Yes, it generates a .a file, but I do not know how to use it in my own CMake-based project...
Also, videoInput compiles and executes well when using the 32 bits version of MinGW.

**Comment by pcha75** [comment]
Hi everybody, 
I managed to compile videoInput using a 64 bits version of MinGW. 
The main problem was the `strmbase.lib` proposed in the official videoInput repository, which is 32 bits compiled version. I replaced the 32 bist `strmbase.lib` by the 64 bits version. You can find it in your own windows 10 operating system here: `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64\strmiids.lib`. 
Just in case, following is a minimal `CMakeLists.txt` that I wrote which allows compiling and executing videoInput: 
```
cmake_minimum_required(VERSION 3.5)

project(mingw-videoInput LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(${PROJECT_NAME}
    "main.cpp"
    "videoInput/videoInput.cpp"
    "videoInput/videoInput.h"
    )

target_include_directories(${PROJECT_NAME} PRIVATE
  DShow/include/
  )

target_link_libraries(${PROJECT_NAME} PRIVATE
    "${CMAKE_SOURCE_DIR}/DShow/lib/strmbase.lib"
    )
```
Good day!

**Comment by pcha75** [comment]
Hi, 
I managed to compile and execute videoInput using the 64 bits version of MinGW: the problem was to link to the right `strmbase.lib`. The one available in videoInput repository is 32 bits compiled version. You need to use the 64 bits version in order to compile and execute videoInput with MinGW 64 bits. You can find the 64 bits version directly in your Windows 10 operating system here: `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64\strmbase.lib`. 
Just in case, following is a minimal `CMakeLists.txt` file that I wrote which compiles and executes videoInput:
```
cmake_minimum_required(VERSION 3.5)

project(mingw-videoInput LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(${PROJECT_NAME}
    "main.cpp" # File where a videoInput object is instanciated.
    "videoInput/videoInput.cpp"
    "videoInput/videoInput.h"
    )

target_include_directories(${PROJECT_NAME} PRIVATE
  DShow/include/
  )

target_link_libraries(${PROJECT_NAME} PRIVATE
    "${CMAKE_SOURCE_DIR}/DShow/lib/strmbase.lib"
    )
```
Good day!
